### PR TITLE
FindJNI: Fix support for Ubuntu

### PR DESCRIPTION
**Pull request by olibre**
My previous contribution was buggy.
This commit provide the correct directories for Ubuntu-based distribution in order to find all neccessary libraries.
The pull request proposes also a tiny clean-up commit.

### CODE REVIEW

**Comment by bradking** [comment]
Thanks.  I applied the main fix as commit 26d16380b077f5a26537fa90f62f90122744bc30 and one of the cleanups as commit 4e11c9660ffd91646438bce4c8898fe62e6456bd.  I've queued the main fix for merge to `release` for 3.6.

**Comment by olibre** [comment]
I will propose a further Pull Request because I have discovered that the tool `update-alternatives --config java` changes a symbolic links (directory).
    
- `/usr/lib/jvm/default-java`   (Ubuntu 16.10)
- `/usr/lib/jvm/default`        (Arch)

I will also add in the file the following command to help detecting such directories on other distros:
    
    find -L /usr/ -name jni.h -printf '%h\n' 2>/dev/null | while read dir ; do while [[ -n $dir ]] ; do dir="${dir%/*}" ; [[ -L $dir ]] && echo "$dir"; done; done

**Comment by bradking** [comment]
@olibre thanks.  Please see `CONTRIBUTING.rst` for the preferred contribution path.

**Comment by olibre** [comment]
@bradking Wonderfull, you have recently changed the [`CONTRIBUTING.rst`](https://github.com/Kitware/CMake/commit/03bd9895e3f0bcdc97f051733728ca8869f8fb9e#diff-ea1f65a8eaac0cec7ae151dfdbbbc587) process :+1: No need to send a patch on mailing list :-)

**Can I still use GitHub or do you prefer I use gitlab.kitware.com?**

**Comment by bradking** [comment]
@olibre please use `gitlab.kitware.com`.  You can register and sign in using your GitHub account (or with a username/password and associate your GitHub account in settings later).

**Pull request closed without merging**
