### PR TITLE
CheckCXXCompilerFlag: Add alternative check that actually runs an executable

### PR DESCRIPTION
**Pull request by KOLANICH**
>Thanks for your interest in contributing to CMake!  The GitHub repository
is a mirror provided for convenience, but CMake does not use GitHub pull
requests for contribution.  Please see
  https://gitlab.kitware.com/cmake/cmake/tree/master/CONTRIBUTING.rst
for contribution instructions.  GitHub OAuth may be used to sign in.

Sorry, but I'm not gonna use your gitlab. It's a big problem to authorise there without granting permissions. 

So I hope that someone will move my PR there.

This PR is because it makes more sense to check whether the code works than compiles. For example adding `-pie` to link flags for the latest MinGW-W64 causes the app not work. It doesn't crashes, just exits.

### CODE REVIEW

**Comment by bradking** [comment]
> I'm not gonna use your gitlab. It's a big problem to authorise there without granting permissions.

GitLab only requests only the very basic "Access user email addresses (read-only)" permission.
Or, you could register an account there with a user name and password independent of GitHub.

As for the change itself, I think the use case should be first discussed in an issue before deciding on a module/function interface for it.

**Comment by KOLANICH** [comment]
>As for the change itself, I think the use case should be first discussed in an issue before deciding on a module/function interface for it.

Could you create that issue for me and attach my PR there?

**Comment by bradking** [comment]
Recorded as [CMake Issue 18191](https://gitlab.kitware.com/cmake/cmake/issues/18191) with a link to this PR.

**Comment by KOLANICH** [comment]
Thank you.

**Comment by KOLANICH** [comment]
@bradking

**Comment by bradking** [comment]
@KOLANICH please see the solution posted [here](https://gitlab.kitware.com/cmake/cmake/-/issues/18191#note_879939).

**Comment by KOLANICH** [comment]
So [`CheckSourceRuns`](https://cmake.org/cmake/help/latest/module/CheckSourceRuns.html). Thank you for bringing my attention to this feature.

**Pull request closed without merging**
