### PR TITLE
Adjust expected error message in FailedSubmit-ftp

### PR DESCRIPTION
**Pull request by tkelman**
Error message from cygwin's curl (using `../bootstrap --system-libs` or `cmake .. -DCMAKE_USE_SYSTEM_LIBRARIES=ON`, then `ctest -V -R ftp` in cygwin) in CTestTestFailedSubmit-ftp was:
`Failed to connect to  port 21: Connection timed out`, causing this test to fail. Slight extension of this expected error message regex catches this version.

### CODE REVIEW

**Comment by rcdailey** [comment]
@bradking Why do you guys not make use of pull requests? It seems you only create patches from them and apply them manually. That's the hard and inconvenient way.

**Comment by bradking** [comment]
We publish this repo on Github so people can conveniently fork it into their own workspace, but this is not the official main repository.  It is just an automatically updated mirror of the real repo, so we can't directly merge here.  Our preferred contribution method is described in `CONTRIBUTING.rst`.  For pull requests with changes requiring multiple rounds of review or broader discussion I close them with a request to go to the mailing list.  For simple changes I just take them, but often want to tweak the commit message as I might when taking a patch from the list.

**Comment by tkelman** [comment]
Thanks for reminding me I have a bunch of patches I need to send to the mailing list...

If this is a one-way mirror then it's not exactly hard given GitHub does convenient things like https://github.com/Kitware/CMake/pull/120.patch for you

**Comment by rcdailey** [comment]
@bradking Thanks for responding. I'll respond again but this probably isn't the best place to have a long discussion on the topic, so please let me know where we can continue the discussion (because I think it's interesting and important, but you guys have probably discussed this already many times).

Where is your official repository and why can't it be on Github (Bitbucket, or any git hosting site in general really)? The issue tracking, pull requests, and other features that Github provides are absolutely amazing and encourage contributions and make it easier. The Linus method of contributions, which you guys seem to be using for the most part, are frustrating and unintuitive. He enforces mailing list patches and such for linux kernel contributions.

Mailing lists are old technology. It's much easier to read and contribute to discussions on a pull request page. Mailing lists are not an appropriate tool to view unified diffs. Not all mail clients will use monospaced fonts and certainly none will apply syntax coloring to the diff view which all make them easier to read.

Using `git format-patch` and `git send-email` are difficult to setup and arguably unintuitive to use when compared to pull requests which simply require clicks of buttons. It's easier for you guys to accept changes via pull requests (one click to merge it) versus using `git am` to apply patches via mail box (which again requires its own complex setup).

It's never made sense to me why people choose to avoid Github's amazing facilities. You could easily import your bugzilla database here and manage issues here. Bugzilla is a huge PITA compared to Github, Bitbucket, etc for issue tracking.

Maybe you guys have your reasons but it's just so crazy to me that we're stuck in the early 1990s when it comes to open source tooling. We need to fast forward to the 21st century and use more modern tooling designed to make open source contributions and involvement easier.

**Pull request closed without merging**
