### PR TITLE
find more binutils -- CMakeFindBinUtils.cmake

### PR DESCRIPTION
**Pull request by ajneu**

### CODE REVIEW

**Comment by ajneu** [comment]
Hmmm... my current pullrequest only includes the size tool.

But I guess the real question is: which other binutils are there?

Here's a table I've now compiled:

|[GNU binutils website](https://www.gnu.org/software/binutils/) | [CMake](https://github.com/Kitware/CMake/blob/4d52cd36ada014bc3e9a65be06b30966cf29f9a8/Modules/CMakeFindBinUtils.cmake#L66)  | [Debian (sid) binutils](https://packages.debian.org/sid/amd64/binutils/filelist) |
| --- | --- | --- |
|`ld` - the GNU linker. |CMAKE_LINKER |`ld`|
| | |`ld.bfd`|
| | |`ld.gold`|
| `as` - the GNU assembler.|cmake finds asm|`as`|
| `addr2line` - Converts addresses into filenames and line numbers.| |`addr2line`|
| `ar` - A utility for creating, modifying and extracting from archives.|CMAKE_AR|`ar`|
| ` c++filt` - Filter to demangle encoded C++ symbols.| |`c++filt`|
| `dlltool` - Creates files for building and using DLLs.| |
| `gold` - A new, faster, ELF only linker, still in beta test.| |`gold`|
| `gprof` - Displays profiling information.| |`gprof`|
| `nlmconv` - Converts object code into an NLM.| |`nm`|
| `nm` - Lists symbols from object files.|CMAKE_NM|
| `objcopy` - Copies and translates object files.|CMAKE_OBJCOPY|`objcopy`|
| `objdump` - Displays information from object files.|CMAKE_OBJDUMP|`objdump`|
| `ranlib` - Generates an index to the contents of an archive.|CMAKE_RANLIB|`ranlib`|
| `readelf` - Displays information from any ELF format object file.| |`readelf`|
| `size` - Lists the section sizes of an object or archive file.| |`size`|
| `strings` - Lists printable strings from files.| |`strings`|
| `strip` - Discards symbols.|CMAKE_STRIP|`strip`|
| `windmc` - A Windows compatible message compiler.| |
| `windres` - A compiler for Windows resource files.| |
| | | `dwp` |
| | | `elfedit` |

I guess it would be good if CMake would support more of these tools.

Comments? Suggestions?
Thanks.

**Comment by ajneu** [comment]
OK, so I've done a 2nd commit in this pull-request, which searches for more binutils.

I'm no expert on cmake, so question: would every binutil need ${_CMAKE_TOOLCHAIN_SUFFIX} ??
In the released cmake version, only `ar` ([ref](https://github.com/Kitware/CMake/blob/4d52cd36ada014bc3e9a65be06b30966cf29f9a8/Modules/CMakeFindBinUtils.cmake#L53)) and `strip` ([ref](https://github.com/Kitware/CMake/blob/4d52cd36ada014bc3e9a65be06b30966cf29f9a8/Modules/CMakeFindBinUtils.cmake#L60)) 
had ${_CMAKE_TOOLCHAIN_SUFFIX}.

Thanks.

**Comment by ajneu** [comment]
The main rationale of this commit, is for cross-compilers, by the way.

Here are examples of relavant programs from various packages:

**Debian**
* Atmel AVR Microcontroller:
 * [binutils-avr](https://packages.debian.org/sid/amd64/binutils-avr/filelist)
 * [gcc-avr](https://packages.debian.org/sid/amd64/gcc-avr/filelist) (`gcc`, `g++`, `ar`, `nm`, `ranlib`, `gcov`)
* gcc-arm-none-eabi
 * [binutils-arm-none-eabi](https://packages.debian.org/sid/amd64/binutils-arm-none-eabi/filelist)
 * [gcc-arm-none-eabi](https://packages.debian.org/sid/amd64/gcc-arm-none-eabi/filelist)  (`gcc`, `g++`, `ar`, `nm`, `ranlib`, `gcov`)

**Comment by bradking** [comment]
Currently the module is intended only to find binutils that CMake needs to reference while generating a build system.  A general-purpose user-facing FindGNUBinutils module could provide more, but should be explicitly requested by a `find_package(GNUBinutils)` call.  OTOH if cross-compiling toolchain files need some of the other tools then it makes sense to provide them through the default module.

**Pull request closed without merging**
