### PR TITLE
Fix findpostgresql

### PR DESCRIPTION
**Pull request by takar**
Fixes the FindPostgreSQL module on recent Debian and Ubuntu systems

### CODE REVIEW

**Comment by bradking** [comment]
Thanks for working on this.  I'll comment on individual commits.

**Comment by bradking** [comment]
Thanks for reverting the relocatable part.  Please also see my comment in takar/CMake@75af1aa17469b2035756f8d73a9b95d762f1aafe about use of `PATH_SUFFIXES` instead of hard-coded paths.

**Comment by takar** [comment]
Hi Brad, thanks for your comments. I agree that the hard-coded paths should be avoided. I'll propose an improved patch later this week.

**Comment by bradking** [comment]
Closing for now.  Please comment when you have updates or read `CONTRIBUTING.rst` and send a patch tothe mailing list.  Thanks!

**Pull request closed without merging**
