### PR TITLE
Add support for setting AppxBundle policy.

### PR DESCRIPTION
**Pull request by thedmd**

### CODE REVIEW

**Comment by bradking** [comment]
Thanks!  Please find a place in the test suite to cover this.  Please also read `CONTRIBUTING.rst`.

**Comment by bradking** [comment]
@thedmd, please see my previous comment about adding a test case.

Cc: @khouzam

**Comment by khouzam** [comment]
@thedm thanks for the change. This should not be restricted though to WindowsStore only as it also works for WindowsPhone on 8.1.

**Comment by bradking** [comment]
Closing for now.  Please also read `CONTRIBUTING.rst` and send an updated patch to the mailing list after revising it based on comments here.

**Pull request closed without merging**
