### PR TITLE
Make it possible to find `Boost::python` w/ various version suffixes

### PR DESCRIPTION
**Pull request by zaufi**
Linux distributions may use different naming conventions regarding Boost Python library. Here is few cases:

* in Gentoo it has `libboost_python-X.Y.*`, where X.Y is a major+minor  Python version;
* Debian/Ubuntu based distros name it as `libboost_python-pyXY.*`;
* some other RPMs can have `libboost_pythonX.*`

To address that differences a new variable was introduced: `Boost_PYTHON_VERSION_TAG`, so caller may specify a suffix he has in a target distribution, so finder would be able to find and import `Boost::python` correctly.

### CODE REVIEW

**Comment by bradking** [comment]
Cc: @mathstuf @rleigh-dundee

**Comment by mathstuf** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/12955

**Comment by zaufi** [comment]
@bradking, @mathstuf, @rleigh-dundee

… any problems w/ this code?

**Comment by rleigh-dundee** [comment]
@zaufi Sorry, I haven't had time to review it yet.  I'll try to get to it today.

**Comment by bradking** [comment]
@zaufi do you mind submitting this (and future changes) through our [GitLab Instance](https://gitlab.kitware.com/cmake/cmake) instead?  Your GitHub account can be used to authenticate.

**Comment by zaufi** [comment]
@bradking , done...

**Comment by bradking** [comment]
Thanks.  Closing this here in favor of [MR 35](https://gitlab.kitware.com/cmake/cmake/merge_requests/35) on our GitLab instance.

**Pull request closed without merging**
