### PR TITLE
CPack-STGZ: use correct sub directory

### PR DESCRIPTION
**Pull request by ThomasVolkert**
This fixes directory naming for me.
Best regards.

### CODE REVIEW

**Comment by bradking** [comment]
The convention for binary release tarballs is that the extraction directory matches the name of the tarball.  That is why `CPACK_PACKAGE_FILE_NAME` is used here.  `CPACK_PACKAGE_INSTALL_DIRECTORY` is documented for use by installer tools like NSIS.  The `STGZ` generator is meant to create self-extracting tarballs that are otherwise the same as the `TGZ` generator.

**Comment by ThomasVolkert** [comment]
Okay, but this means that with every new release of the software a new folder name would be used (assuming that CPACK_PACKAGE_FILE_NAME contains some versioning). Is there some way currently available to use the following scheme?:

folder: ${FIXED_NAME}
sh file: ${FIXED_NAME}_${VERSIONING}.sh

**Comment by bradking** [comment]
No, because that breaks the widely-used convention that extracting a tgz produces a directory with the same name.  This convention is not CMake-specific.  It has existed for decades and should be respected.  Among the reasons for this is that extracting different versions in the same working directory should not clobber each other's files.  If one extracts and then manually renames the directory to a version-less name then that latter step will detect such collisions.

If you want a full installer tool then look at the Qt IFW generator.

**Comment by ThomasVolkert** [comment]
Thanks for the feedback. We can skip this patch.

**Pull request closed without merging**
